version: '3.8'

services:

  redis:
    image: redis:7.2.4-alpine3.19
    container_name: redis
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf:ro

  nginx:
    image: nginx:1.25.1
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy

  backend:
    image: docker-compose-example-backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: backend
    # Env vars could be declared here, but I'm used to keep then in .env files. Prod security checks and considerations are needed. All sensible env vars in prod should be initialized in different way
    env_file:
      - ./.docker-env
    depends_on:
      - nginx
      - redis